apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
stringData:
    POSTGRES_DATABASE: d8a83okpmod82a
    POSTGRES_EXTERNAL_ADDRESS: postgres://ldivyrmxdfzrhe:dc3db58aaa0234176913138143ac86114d42aebbd2dfd547561c53afeb5a8c58@ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d8a83okpmod82a
    POSTGRES_PASSWORD: dc3db58aaa0234176913138143ac86114d42aebbd2dfd547561c53afeb5a8c58
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: "true"
    POSTGRES_USERNAME: ldivyrmxdfzrhe
    SSLMODE: disable
type: Opaque